### ISSUE TITLE
[RFC] Branchless + Crypto robust vs Clarity/Maintainability vs Speed

### ISSUE THREAD

**Issue by mratsim** [status-im/mpint#1]
While implementing the shifting operation ``shl`` and ``shr``, I've come upon what might be an important trade-off of the library:

**Branchless and cryptographically robust implementation**
vs
**Clear, maintainable**
vs
**Fast**

Case in point, here are 2 implementations for `shl`

**Implementation 1**
with branches, seems fast on x86_64, unknown speed on ARM, readable
```Nim
proc `shl`*[T: MpUint](x: T, y: SomeInteger): T {.noInit, noSideEffect.}=
  ## Compute the `shift left` operation of x and y

  if y == 0:
    return x

  let # cannot be const, compile-time sizeof only works for simple types
    size = (T.sizeof * 8)
    halfSize = size div 2

  type Sub = getSubType T

  if y < halfSize:
    result.hi = (x.hi shl y) or (x.lo shr (halfSize - y))
    result.lo = x.lo shl y
  else:
    result.hi = x.lo shl (y - halfSize)
    result.lo = 0.Sub
```
**Implementation 2**
branchless, unconclusive slow/fast on x86_64, unknown speed on ARM, a bit like magic
```Nim
proc `shl`*[T: MpUint](x: T, y: SomeInteger): T {.noInit, noSideEffect.}=
  ## Compute the `shift left` operation of x and y
  type Sub = getSubType T

  let # cannot be const, compile-time sizeof only works for simple types
    size = Sub(T.sizeof * 8)
    halfSize = size div 2

  var S = y.Sub and (size-1) # y mod size

  let
    M1 = Sub( ((((S + size-1) or S) and halfSize) div halfSize) - 1)
    M2 = Sub( (S div halfSize) - 1)

  S = S and (halfSize-1) # y mod halfsize

  result.hi = (x.lo shl S) and not M2
  result.lo = (x.lo shl S) and M2
  result.hi = result.hi or ((
    x.hi shl S or (x.lo shr (size - S) and M1)
  ) and M2)
```
**Implementation 3**
A third implementation would be to cast the MpUint to an array of bytes and use a for loop to shift + carry. It has the advantage of:
  - being iterative instead of recursive like the 2 others (easier for the compiler to optimize and probably recognize what is intended)

and the disadvantages of:
  - working 8 bits by 8 bits instead of 64 by 64. 
  - Short of using ASM (which would not be portable) dealing with the carry
  - Branching in a for loop due to the carry
  - Need a big endian and little endian implementation

**Comment by alehander42** [comment]
Just IMO, in a case like that even a bit more complicated and "magic" implementation would be fine if it's documented and tested well, as this will be still not a huge cost for an important performance benefit. (bigint operations would be a hotspot)
